{
 "title": "Cetogenix Reactors",
 "description": "Dashboard for monitoring the Low Rate Reactors (LRR) as part of the BPA project",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Reactor Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] =~ /^pico_[1-4]$/) // Matches pico_1, pico_2, pico_3, pico_4\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pH\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Reactor \" + strings.substring(v: r.device, start: 5, end: 6) + \" pH\", // Labels as \"Pico 1 pH\"\r\n\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")\r\n"
    }
   ]
  },
  {
   "title": "ORP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] =~ /^pico_[1-4]$/) // Matches pico_1, pico_2, pico_3, pico_4\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ORP\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Reactor \" + strings.substring(v: r.device, start: 5, end: 6) + \" ORP\", \r\n\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] =~ /^pico_[1-4]$/) // Matches pico_1, pico_2, pico_3, pico_4\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Reactor \" + strings.substring(v: r.device, start: 5, end: 6) + \" Temperature\", \r\n\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")\r\n"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] =~ /^pico_[1-4]$/) // Matches pico_1, pico_2, pico_3, pico_4\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RPM\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Reactor \" + strings.substring(v: r.device, start: 5, end: 6) + \" RPM\", \r\n\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")\r\n"
    }
   ]
  },
  {
   "title": "Motor Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] =~ /^pico_[1-2]$/) // Matches pico_1, pico_2, pico_3, pico_4\r\n  |> filter(fn: (r) => r[\"_field\"] == \"motor_mA\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Reactor \" + strings.substring(v: r.device, start: 5, end: 6) + \" Motor Current (mA)\", \r\n\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")\r\n"
    }
   ]
  },
  { "title": "Flow Meter Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Flow Normalised (mL/min)",
   "type": "timeseries",
   "description": "Moving Average over last 10readings",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^gas_meter_[1-4]$/) \r\n  |> filter(fn: (r) => r[\"_field\"] == \"Flow Normalised (mL/min)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) // Smooths based on the dashboard time window\r\n  |> movingAverage(n: 10) \r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Gas Meter \" + strings.substring(v: r._measurement, start: 10, end: 11) + \" - Flow Normalised (mL/min)\"\r\n  }))\r\n  |> yield(name: \"gas_meters\")\r\n"
    }
   ]
  },
  {
   "title": "Volume Normalised (mL)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_4\" or r[\"_measurement\"] == \"gas_meter_3\" or r[\"_measurement\"] == \"gas_meter_2\" or r[\"_measurement\"] == \"gas_meter_1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Volume Normalised (mL)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flow (mL/min)",
   "type": "timeseries",
   "description": "Moving average over last 1 reading",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^gas_meter_[1-4]$/) // Matches gas_meter_1 to gas_meter_4\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Flow (mL/min)\")\r\n  |> movingAverage(n: 1) // Smooths spikes by averaging over the last 1000 readings\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Gas Meter \" + strings.substring(v: r._measurement, start: 10, end: 11) + \" - Flow (mL/min)\",\r\n\r\n  }))\r\n  |> yield(name: \"gas_meters\")\r\n"
    }
   ]
  },
  {
   "title": "Volume (mL)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_4\" or r[\"_measurement\"] == \"gas_meter_3\" or r[\"_measurement\"] == \"gas_meter_2\" or r[\"_measurement\"] == \"gas_meter_1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Volume (mL)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_4\" or r[\"_measurement\"] == \"gas_meter_3\" or r[\"_measurement\"] == \"gas_meter_2\" or r[\"_measurement\"] == \"gas_meter_1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Pressure (hPa)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flow Meter Temp (Room Temp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_4\" or r[\"_measurement\"] == \"gas_meter_3\" or r[\"_measurement\"] == \"gas_meter_2\" or r[\"_measurement\"] == \"gas_meter_1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature (°C)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery (V)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_4\" or r[\"_measurement\"] == \"gas_meter_3\" or r[\"_measurement\"] == \"gas_meter_2\" or r[\"_measurement\"] == \"gas_meter_1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Battery (V)\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reactor 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Flow (mL/min)\" \r\n      or r[\"_field\"] == \"Power Supply (V)\" \r\n      or r[\"_field\"] == \"Flow Normalised (mL/min)\" \r\n      or r[\"_field\"] == \"Pressure (hPa)\" \r\n      or r[\"_field\"] == \"Temperature (°C)\" \r\n      or r[\"_field\"] == \"Volume (mL)\" \r\n      or r[\"_field\"] == \"Volume Normalised (mL)\" \r\n      or r[\"_field\"] == \"Battery (V)\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Gas Meter 1 - \" + r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"pico_1\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"pH\" or r[\"_field\"] == \"ORP\" or r[\"_field\"] == \"motor_mA\" or r[\"_field\"] == \"RPM\")\r\n//   // Filter out unreasonable values (adjust thresholds as needed).  Use the *engineering unit* ranges.\r\n//   |> filter(fn: (r) => \r\n//       (r._field == \"motor_mA\"    and r._value <  2000 and r._value >= -5) and\r\n//       (r._field == \"Temperature\" and r._value <  110  and r._value >= -1) and\r\n//       (r._field == \"pH\"          and r._value <  14.5 and r._value >= -0.5) and\r\n//       (r._field == \"ORP\"         and r._value <  2100 and r._value >= -2100) and\r\n//       (r._field == \"RPM\"         and r._value < 60000 and r._value >= -1)\r\n//     )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Pico \" + strings.substring(v: r.device, start: 5, end: 6) + \" - \" + r._field //Simplified field naming\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")"
      }
     ]
    },
    {
     "title": "Reactor 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Flow (mL/min)\" \r\n      or r[\"_field\"] == \"Power Supply (V)\" \r\n      or r[\"_field\"] == \"Flow Normalised (mL/min)\" \r\n      or r[\"_field\"] == \"Pressure (hPa)\" \r\n      or r[\"_field\"] == \"Temperature (°C)\" \r\n      or r[\"_field\"] == \"Volume (mL)\" \r\n      or r[\"_field\"] == \"Volume Normalised (mL)\" \r\n      or r[\"_field\"] == \"Battery (V)\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Gas Meter 2 - \" + r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"pico_2\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"pH\" or r[\"_field\"] == \"ORP\" or r[\"_field\"] == \"motor_mA\" or r[\"_field\"] == \"RPM\")\r\n//   // Filter out unreasonable values (adjust thresholds as needed).  Use the *engineering unit* ranges.\r\n//   |> filter(fn: (r) => \r\n//       (r._field == \"motor_mA\"    and r._value <  2000 and r._value >= -5) and\r\n//       (r._field == \"Temperature\" and r._value <  110  and r._value >= -1) and\r\n//       (r._field == \"pH\"          and r._value <  14.5 and r._value >= -0.5) and\r\n//       (r._field == \"ORP\"         and r._value <  2100 and r._value >= -2100) and\r\n//       (r._field == \"RPM\"         and r._value < 60000 and r._value >= -1)\r\n//     )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Pico \" + strings.substring(v: r.device, start: 5, end: 6) + \" - \" + r._field //Simplified field naming\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")"
      }
     ]
    },
    {
     "title": "Reactor 3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Flow (mL/min)\" \r\n      or r[\"_field\"] == \"Power Supply (V)\" \r\n      or r[\"_field\"] == \"Flow Normalised (mL/min)\" \r\n      or r[\"_field\"] == \"Pressure (hPa)\" \r\n      or r[\"_field\"] == \"Temperature (°C)\" \r\n      or r[\"_field\"] == \"Volume (mL)\" \r\n      or r[\"_field\"] == \"Volume Normalised (mL)\" \r\n      or r[\"_field\"] == \"Battery (V)\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Gas Meter 3 - \" + r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"pico_3\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"pH\" or r[\"_field\"] == \"ORP\" or r[\"_field\"] == \"motor_mA\" or r[\"_field\"] == \"RPM\")\r\n//   // Filter out unreasonable values (adjust thresholds as needed).  Use the *engineering unit* ranges.\r\n//   |> filter(fn: (r) => \r\n//       (r._field == \"motor_mA\"    and r._value <  2000 and r._value >= -5) and\r\n//       (r._field == \"Temperature\" and r._value <  110  and r._value >= -1) and\r\n//       (r._field == \"pH\"          and r._value <  14.5 and r._value >= -0.5) and\r\n//       (r._field == \"ORP\"         and r._value <  2100 and r._value >= -2100) and\r\n//       (r._field == \"RPM\"         and r._value < 60000 and r._value >= -1)\r\n//     )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Pico \" + strings.substring(v: r.device, start: 5, end: 6) + \" - \" + r._field //Simplified field naming\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")"
      }
     ]
    },
    {
     "title": "Reactor 4",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "query": "from(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_meter_4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Flow (mL/min)\" \r\n      or r[\"_field\"] == \"Power Supply (V)\" \r\n      or r[\"_field\"] == \"Flow Normalised (mL/min)\" \r\n      or r[\"_field\"] == \"Pressure (hPa)\" \r\n      or r[\"_field\"] == \"Temperature (°C)\" \r\n      or r[\"_field\"] == \"Volume (mL)\" \r\n      or r[\"_field\"] == \"Volume Normalised (mL)\" \r\n      or r[\"_field\"] == \"Battery (V)\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Gas Meter 4 - \" + r._field\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
      },
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"reactor-monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pico_measurements\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"pico_4\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"pH\" or r[\"_field\"] == \"ORP\" or r[\"_field\"] == \"motor_mA\" or r[\"_field\"] == \"RPM\")\r\n//   // Filter out unreasonable values (adjust thresholds as needed).  Use the *engineering unit* ranges.\r\n//   |> filter(fn: (r) => \r\n//       (r._field == \"motor_mA\"    and r._value <  2000 and r._value >= -5) and\r\n//       (r._field == \"Temperature\" and r._value <  110  and r._value >= -1) and\r\n//       (r._field == \"pH\"          and r._value <  14.5 and r._value >= -0.5) and\r\n//       (r._field == \"ORP\"         and r._value <  2100 and r._value >= -2100) and\r\n//       (r._field == \"RPM\"         and r._value < 60000 and r._value >= -1)\r\n//     )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      _field: \"Pico \" + strings.substring(v: r.device, start: 5, end: 6) + \" - \" + r._field //Simplified field naming\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"picos\")"
      }
     ]
    }
   ]
  }
 ]
}